import { useState, type FormEvent } from "react";
import { AlertTriangle, KeyRound, Mail } from "lucide-react";
import Card from "../../components/common/Card";
import Input from "../../components/common/Input";
import Button from "../../components/common/Button";
import Modal from "../../components/common/Modal";
import { ApiError } from "../../config/api";
import { authApi } from "../auth/api/authApi";
import { useAuth } from "../auth/context/AuthContext";
import { useToast } from "../../context/ToastContext";

const errorMessage = (error: unknown) => error instanceof ApiError ? error.details.message : "Le serveur est indisponible.";
export default function AccountSettings() {
  const { user, updateProfile, refreshUser } = useAuth(); const { addToast } = useToast();
  const [name, setName] = useState(user?.displayName ?? ""); const [profileLoading, setProfileLoading] = useState(false);
  const [newEmail, setNewEmail] = useState(""); const [emailPassword, setEmailPassword] = useState(""); const [emailLoading, setEmailLoading] = useState(false);
  const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [confirmation, setConfirmation] = useState(""); const [passwordLoading, setPasswordLoading] = useState(false);
  const [deletePassword, setDeletePassword] = useState(""); const [deleteOpen, setDeleteOpen] = useState(false); const [deleteLoading, setDeleteLoading] = useState(false);
  const submitProfile = async (event: FormEvent) => { event.preventDefault(); setProfileLoading(true); try { await updateProfile(name); addToast("success", "Profil mis à jour", "Votre nom affiché a été enregistré."); } catch (error) { addToast("info", "Mise à jour impossible", errorMessage(error)); } finally { setProfileLoading(false); } };
  const submitEmail = async (event: FormEvent) => { event.preventDefault(); setEmailLoading(true); try { await authApi.changeEmail(newEmail, emailPassword); await refreshUser(); setNewEmail(""); setEmailPassword(""); addToast("success", "Adresse email mise à jour", "Votre nouvelle adresse est active."); } catch (error) { addToast("info", "Mise à jour impossible", errorMessage(error)); } finally { setEmailLoading(false); } };
  const submitPassword = async (event: FormEvent) => { event.preventDefault(); if (newPassword !== confirmation) { addToast("info", "Mise à jour impossible", "Les mots de passe ne correspondent pas."); return; } setPasswordLoading(true); try { await authApi.changePassword(currentPassword, newPassword); setCurrentPassword(""); setNewPassword(""); setConfirmation(""); addToast("success", "Mot de passe modifié", "Une nouvelle session sécurisée est active."); } catch (error) { addToast("info", "Mise à jour impossible", errorMessage(error)); } finally { setPasswordLoading(false); } };
  const submitDelete = async () => { setDeleteLoading(true); try { await authApi.deleteAccount(deletePassword); window.location.assign("/login"); } catch (error) { addToast("info", "Suppression impossible", errorMessage(error)); setDeleteLoading(false); } };
  return <div className="account-settings">
    <Card title="Profil"><form className="form-grid" onSubmit={submitProfile}><Input id="account-name" label="Nom affiché" value={name} onChange={(e) => setName(e.target.value)} autoComplete="name" required /><Input id="account-email" label="Email actuel" value={user?.email ?? ""} readOnly type="email" /><Button type="submit" disabled={profileLoading}>{profileLoading ? "Enregistrement..." : "Enregistrer"}</Button></form></Card>
    <Card title="Adresse email"><form className="form-grid" onSubmit={submitEmail}><p className="account-help"><Mail size={18} /> Le changement est immédiat pour ce compte local.</p><Input id="new-email" label="Nouvelle adresse email" type="email" value={newEmail} onChange={(e) => setNewEmail(e.target.value)} autoComplete="email" required /><Input id="email-current-password" label="Mot de passe actuel" type="password" value={emailPassword} onChange={(e) => setEmailPassword(e.target.value)} autoComplete="current-password" required /><Button type="submit" disabled={emailLoading}>{emailLoading ? "Mise à jour..." : "Changer l’adresse email"}</Button></form></Card>
    <Card title="Sécurité"><form className="form-grid" onSubmit={submitPassword}><p className="account-help"><KeyRound size={18} /> 10 caractères minimum pour un nouveau mot de passe.</p><Input id="current-password" label="Mot de passe actuel" type="password" value={currentPassword} onChange={(e) => setCurrentPassword(e.target.value)} autoComplete="current-password" required /><Input id="new-password" label="Nouveau mot de passe" type="password" value={newPassword} onChange={(e) => setNewPassword(e.target.value)} autoComplete="new-password" minLength={10} required /><Input id="new-password-confirmation" label="Confirmation" type="password" value={confirmation} onChange={(e) => setConfirmation(e.target.value)} autoComplete="new-password" required /><Button type="submit" disabled={passwordLoading}>{passwordLoading ? "Modification..." : "Changer le mot de passe"}</Button></form></Card>
    <Card title="Zone dangereuse"><div className="danger-zone"><div><h3>Supprimer mon compte</h3><p>Cette action supprime définitivement votre compte local et toutes ses sessions.</p></div><Button variant="danger" onClick={() => setDeleteOpen(true)}><AlertTriangle size={17} /> Supprimer mon compte</Button></div></Card>
    <Modal isOpen={deleteOpen} onClose={() => setDeleteOpen(false)} title="Confirmer la suppression" width="sm"><p>Cette action est définitive. Saisissez votre mot de passe pour continuer.</p><Input id="delete-password" label="Mot de passe actuel" type="password" value={deletePassword} onChange={(e) => setDeletePassword(e.target.value)} autoComplete="current-password" autoFocus /><div className="account-modal-actions"><Button variant="ghost" onClick={() => setDeleteOpen(false)}>Annuler</Button><Button variant="danger" disabled={!deletePassword || deleteLoading} onClick={() => void submitDelete()}>{deleteLoading ? "Suppression..." : "Supprimer définitivement"}</Button></div></Modal>
  </div>;
}
