import { randomUUID } from "node:crypto";
import { afterAll, describe, expect, it } from "vitest";
import { prisma } from "../../infrastructure/database/prisma.js";
import { ensureWorkspace } from "./ensureWorkspace.js";
import { adjustStock, createProduct } from "./catalogService.js";
import { recordStockCount } from "./stockCountService.js";
import { createRecipe, recordProduction } from "./recipeService.js";
import { getImpactReport } from "./impactService.js";
import { getOperationalReport } from "./reportService.js";
import { recordWaste, listWaste } from "./wasteService.js";
const users: string[] = [];
afterAll(async () => { await prisma.user.deleteMany({ where: { id: { in: users } } }); await prisma.$disconnect(); });
describe("lot and waste mutations", () => {
  it("keeps stock and allocations atomic, rejects foreign lots and does not re-deduct cooked waste", async () => {
    const email = `lot-test-${randomUUID()}@example.com`;
    const owner = await prisma.user.create({ data: { email, emailNormalized: email, displayName: "Lot fixture", passwordHash: "not-a-login" } });
    users.push(owner.id);
    const workspace = await ensureWorkspace(owner.id);
    const supplier = await prisma.supplier.findFirstOrThrow({ where: { restaurantId: workspace.id } });
    const restaurantId = workspace.id;
    const product = await createProduct(restaurantId, owner.id, { name: "Isolated potato", category: "Légumes", unit: "kg", currentStock: 10, minThreshold: 1, supplierId: supplier.id, pricePerUnit: 2 }, randomUUID());
    const initial = await prisma.stockLot.findFirstOrThrow({ where: { restaurantId, productId: product.id } });
    expect(initial.receivedAt).toBeNull(); expect(initial.expiresAt).toBeNull();
    await prisma.stockLot.update({ where: { id: initial.id }, data: { expiresAt: new Date("2025-12-31") } });
    const expiredRecipe = await createRecipe(restaurantId, owner.id, randomUUID(), { name: "Expired fixture", category: "Plat", prepTime: 1, yieldPortions: 1, effectiveFrom: "2026-01-01", ingredients: [{ productId: product.id, quantity: 1 }] });
    await expect(recordProduction(restaurantId, owner.id, { operationId: randomUUID(), recipeId: expiredRecipe.id, expectedRecipeRevision: 1, recipeName: expiredRecipe.name, portions: 1, prepTime: 1, notes: "", date: "2026-01-01", kind: "production" })).rejects.toMatchObject({ code: "INSUFFICIENT_LOT_STOCK" });
    expect(Number((await prisma.product.findUniqueOrThrow({ where: { restaurantId_id: { restaurantId, id: product.id } } })).currentStock)).toBe(10);
    await prisma.stockLot.update({ where: { id: initial.id }, data: { expiresAt: new Date("2026-02-01"), unitCost: 2 } });
    await adjustStock(restaurantId, owner.id, product.id, -2, randomUUID(), "adjustment");
    expect(Number((await prisma.stockLot.findUniqueOrThrow({ where: { id: initial.id } })).remainingQuantity)).toBe(8);
    const current = await prisma.product.findUniqueOrThrow({ where: { restaurantId_id: { restaurantId, id: product.id } } });
    await recordStockCount(restaurantId, owner.id, product.id, { operationId: randomUUID(), expectedStockRevision: current.stockRevision, expectedUnit: "kg", countedQuantity: 9 });
    const lots = await prisma.stockLot.findMany({ where: { restaurantId, productId: product.id } });
    expect(lots.reduce((sum, lot) => sum + Number(lot.remainingQuantity), 0)).toBe(9);
    const recipe = await createRecipe(restaurantId, owner.id, randomUUID(), { name: "Beverage fixture", category: "Boisson", prepTime: 5, yieldPortions: 2, effectiveFrom: "2026-01-01", ingredients: [{ productId: product.id, quantity: 2, netQuantity: 1.5 }] });
    expect(recipe.category).toBe("Boisson");
    const production = await recordProduction(restaurantId, owner.id, { operationId: randomUUID(), recipeId: recipe.id, expectedRecipeRevision: 1, recipeName: recipe.name, portions: 2, prepTime: 5, notes: "", date: "2026-01-01", serviceSlot: "lunch", kind: "production" });
    const parure = { operationId: randomUUID(), serviceDate: "2026-01-01", kind: "preparation" as const, avoidability: "inedible" as const, productionId: production.id, productId: product.id, quantity: 0.5, unit: "kg", note: "Parures mesurées" };
    expect((await recordWaste(restaurantId, owner.id, parure)).stockMovementId).toBeNull();
    await expect(recordWaste(restaurantId, owner.id, { ...parure, operationId: randomUUID(), quantity: 0.1 })).rejects.toMatchObject({ code: "PREPARATION_WASTE_EXCEEDS_YIELD" });
    const input = { operationId: randomUUID(), serviceDate: "2026-01-01", serviceSlot: "lunch", kind: "unsold" as const, avoidability: "avoidable" as const, productionId: production.id, quantity: 1, unit: "portion", note: "Confirmed discard" };
    const waste = await recordWaste(restaurantId, owner.id, input);
    expect(waste.stockMovementId).toBeNull(); expect((await recordWaste(restaurantId, owner.id, input)).id).toBe(waste.id);
    expect(Number((await prisma.product.findUniqueOrThrow({ where: { restaurantId_id: { restaurantId, id: product.id } } })).currentStock)).toBe(7);
    await expect(recordWaste(restaurantId, owner.id, { ...input, operationId: randomUUID(), quantity: 2 })).rejects.toMatchObject({ code: "WASTE_EXCEEDS_PRODUCTION" });
    await expect(recordWaste(restaurantId, owner.id, { operationId: randomUUID(), serviceDate: "2026-01-01", kind: "raw", avoidability: "avoidable", productId: product.id, lotId: randomUUID(), quantity: 1, unit: "kg", note: "" })).rejects.toMatchObject({ code: "INVALID_LOT" });
    expect(Number((await prisma.product.findUniqueOrThrow({ where: { restaurantId_id: { restaurantId, id: product.id } } })).currentStock)).toBe(7);
    const raw = await recordWaste(restaurantId, owner.id, { operationId: randomUUID(), serviceDate: "2026-01-01", kind: "raw", avoidability: "avoidable", productId: product.id, lotId: initial.id, quantity: 0.25, unit: "kg", note: "Measured raw loss" });
    expect((await listWaste(restaurantId)).find((row) => row.id === raw.id)).toMatchObject({ cost: 0.5, valuation: "lot_cost" });
    expect(Number((await prisma.product.findUniqueOrThrow({ where: { restaurantId_id: { restaurantId, id: product.id } } })).currentStock)).toBe(6.75);
    const currentLots = await prisma.stockLot.findMany({ where: { restaurantId, productId: product.id } });
    expect(currentLots.reduce((sum, row) => sum + Number(row.remainingQuantity), 0)).toBe(6.75);
    const datedRaw = await recordWaste(restaurantId, owner.id, { operationId: randomUUID(), serviceDate: "2026-01-31", kind: "raw", avoidability: "avoidable", productId: product.id, lotId: initial.id, quantity: 0.5, unit: "kg", note: "Backdated service declaration" });
    await recordWaste(restaurantId, owner.id, { ...input, operationId: randomUUID(), serviceDate: "2026-02-01", kind: "plate_return", quantity: 1 });
    const impact = await getImpactReport(restaurantId, "2026-01-01", "2026-02-28", prisma, { includeMonthly: true });
    expect(impact.current.recorded.lossMovementCount).toBe(2);
    expect(impact.current.recorded.knownLossCost).toBe(1.5);
    expect(impact.current.recorded.lossesByProduct[0].quantity).toBe(0.75);
    expect(impact.current.recorded.declaredWaste.records).toHaveLength(5);
    expect(impact.current.recorded.declaredWaste.totals).toContainEqual({ kind: "preparation", avoidability: "inedible", unit: "kg", quantity: 0.5, recordCount: 1 });
    expect(impact.current.recorded.declaredWaste.totals).toContainEqual({ kind: "plate_return", avoidability: "avoidable", unit: "portion", quantity: 1, recordCount: 1 });
    if (!("monthly" in impact)) throw new Error("Monthly projection missing");
    expect(impact.monthly?.find((row) => row.month === "2026-01")?.recorded).toMatchObject({ lossMovementCount: 2, knownLossCost: 1.5 });
    expect(impact.monthly?.find((row) => row.month === "2026-02")?.recorded).toMatchObject({ lossMovementCount: 0, knownLossCost: 0 });
    const report = await getOperationalReport(restaurantId, "2026-01-31", "2026-01-31");
    expect(report.declaredWaste.records.map((row) => row.id)).toEqual([datedRaw.id]);
    expect(report.declaredLosses.reportedMovementCount).toBe(1);
    expect(report.rows.filter((row) => row.section === "Pertes et déchets déclarés par service")).toHaveLength(2);
    expect(report.rows.find((row) => row.metric === "Coût connu des lots (EUR)")?.value).toBe("1.00");
    const withoutDouble = await prisma.product.findUniqueOrThrow({ where: { restaurantId_id: { restaurantId, id: product.id } } });
    expect(Number(withoutDouble.currentStock)).toBe(6.25);
    await prisma.product.update({ where: { restaurantId_id: { restaurantId, id: product.id } }, data: { unit: "L" } });
    const retainedUnit = await getImpactReport(restaurantId, "2026-01-01", "2026-02-28");
    expect(retainedUnit.current.recorded.lossesByProduct[0]).toMatchObject({ unit: "kg", quantity: 0.75, knownCost: 1.5 });
    expect(retainedUnit.current.recorded.declaredWaste.totals.some((row) => row.unit === "L")).toBe(false);


  });
});
